"""
The schema root for mutating data
"""
type Mutation {
  """
  Emit a string to test subsctiptions
  """
  emitString(value: String!): String

  """
  Sets the mutableField. Used to test mutation tpe operations.
  """
  setMutableField(value: String!): String
}

"""
The schema root for fetching data.
"""
type Query {
  """
  Returns the mutable field used to test the mutation result.
  """
  mutableField: String

  """
  Used to test query type operations. Returns a random string.
  """
  queriableField: String
  queryForError: String
}

"""
The schema root for subscriptions
"""
type Subscription {
  """
  Used to test subscriptions.
  """
  subscribableCount: Int
  subscribeForError: String

  """
  Used to test subscriptions.
  """
  subscribeToEmittedString(browserId: String!): String
}
