"""
The schema root for mutating data
"""
type Mutation {
  """
  Emit a string to test subsctiptions
  """
  emitString(value: String!): String
  mutateField(suffix: String): String
  mutateField2(suffix: String): String
}

"""
The schema root for fetching data.
"""
type Query {
  description: String
  mutableField(prefix: String): String
  mutationCount: String
  name: String
  queryForError: String
}

"""
The schema root for subscriptions
"""
type Subscription {
  subscribeEmitter: String
  subscribeForError: String
  subscribeIterator(suffix: String): String
}
