name: CI/CD Pipeline

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  check-and-test-publish:
    strategy:
      matrix:
        node: [22, 24]
    runs-on: ubuntu-latest
    outputs:
      urls: ${{ steps.pkgprnew.outputs.urls }}
    steps:
      # v7
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

        # v2
      - uses: pnpm/setup@84cb39b217b10273981911c288cd62326dc7c6d2
        with:
          runtime: node@${{ matrix.node }}
          version: 11

      - run: pnpm ci
      - run: pnpm exec prettier --write ./pnpm-lock.yaml
      - run: pnpm run check

      - name: Upload to pkgprnew
        id: pkgprnew
        if: matrix.node == 24
        run: pnpm dlx pkg-pr-new publish

  test-published-package:
    runs-on: ubuntu-latest
    needs: check-and-test-publish
    strategy:
      matrix:
        graphql-ws-peer: ['5.5.5', '^6.0.0']
    steps:
      # v7
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - uses: pnpm/setup@84cb39b217b10273981911c288cd62326dc7c6d2
        with:
          runtime: node@24
          version: 11

      - run: pnpm ci

      # Add the peer dependency with the version to be tested.
      - run: pnpm add --filter="e2e-web-app" graphql-ws@${{ matrix.graphql-ws-peer }}

      # Add the published package. It will have its own version of the peer dependency.
      - name: Install the published package for testing
        run: pnpm add --filter="e2e-web-app" graphql-shared-ws@https://pkg.pr.new/sdev-buildz/graphql-shared-ws/graphql-shared-ws@${{github.sha}}

      - name: Run tests against the published package
        run: pnpm run e2e:ci
